# Generated by Django 4.0.4 on 2022-04-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_customer_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='name1',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Customer',
        ),
    ]
