# Generated by Django 4.0.4 on 2022-04-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0005_rename_name_customer_name1_alter_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
